apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  username: OTY1ODkxYWY=
  password: VzFqQWlWOHVOWGZmcHc=
  replication_user: cmVwbHVzZXI= # base64 encoded 'repluser'
  replication_password: cmVwbHBhc3N3b3Jk # base64 encoded 'replpassword'
