apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  namespace: {{ .Values.app.namespace}}
spec:
  ports:
  - nodePort: {{ .Values.service.nodeport}}
    port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.service.port}}
  selector:
    app: {{ .Values.app.name}}
  type: LoadBalancer
