global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["app:6969"]

  - job_name: "kaas api"
    static_configs:
      - targets: ["app:7001"]
